#ifndef CORE_OBJECT_TYPE_H
#define CORE_OBJECT_TYPE_H

typedef enum {
	TYPE_PTR = 1,
	TYPE_ALLOCATION_BLOCK = 2,
	TYPE_ALLOCATOR = 3,
	TYPE_STRING = 100,
	TYPE_STRING_DATA = 101,
	TYPE_DICTIONARY = 111,
	TYPE_DICTIONARY_KVP = 112,
	TYPE_DICTIONARY_BUCKETS = 113
} object_type;

#endif // CORE_OBJECT_TYPE_H
